### ISSUE TITLE
Render Joystick error page in browser when esbuild fails

### ISSUE THREAD

**Issue by rglover** [cheatcode/joystick#20]
This was wired up for Rollup but isn't working with esbuild. Need to refactor.

**Comment by rglover** [comment]
Also make sure to utilize the existing onWarn script. Paths to errors will be different but should still be able to get a nice output in the terminal.

**Comment by rglover** [comment]
Looks like error parsing will be pretty straightforward. Can just grab the error/exception in a try/catch and format:

```javascript
----->> Building app...HERE 3 SyntaxError: Unexpected token (10:8)
    at Parser.pp$5.raise (file:///usr/local/lib/node_modules/@joystick.js/cli/node_modules/acorn/dist/acorn.mjs:3410:13)
    at Parser.pp.unexpected (file:///usr/local/lib/node_modules/@joystick.js/cli/node_modules/acorn/dist/acorn.mjs:735:8)
    at Parser.pp.expect (file:///usr/local/lib/node_modules/@joystick.js/cli/node_modules/acorn/dist/acorn.mjs:729:26)
    at Parser.pp$4.parseObj (file:///usr/local/lib/node_modules/@joystick.js/cli/node_modules/acorn/dist/acorn.mjs:3022:12)
    at Parser.pp$4.parseExprAtom (file:///usr/local/lib/node_modules/@joystick.js/cli/node_modules/acorn/dist/acorn.mjs:2761:17)
    at Parser.pp$4.parseExprSubscripts (file:///usr/local/lib/node_modules/@joystick.js/cli/node_modules/acorn/dist/acorn.mjs:2577:19)
    at Parser.pp$4.parseMaybeUnary (file:///usr/local/lib/node_modules/@joystick.js/cli/node_modules/acorn/dist/acorn.mjs:2543:17)
    at Parser.pp$4.parseExprOps (file:///usr/local/lib/node_modules/@joystick.js/cli/node_modules/acorn/dist/acorn.mjs:2476:19)
    at Parser.pp$4.parseMaybeConditional (file:///usr/local/lib/node_modules/@joystick.js/cli/node_modules/acorn/dist/acorn.mjs:2459:19)
    at Parser.pp$4.parseMaybeAssign (file:///usr/local/lib/node_modules/@joystick.js/cli/node_modules/acorn/dist/acorn.mjs:2427:19) {
  pos: 370,
  loc: Position { line: 10, column: 8 },
  raisedAt: 376
}
 > ui/pages/training/index.js:10:8: error: Expected "}" but found "button"
    10 │         button: {
       ╵         ~~~~~~

Error: Build failed with 1 error:
ui/pages/training/index.js:10:8: error: Expected "}" but found "button"
    at failureErrorWithLog (/usr/local/lib/node_modules/@joystick.js/cli/node_modules/esbuild/lib/main.js:1495:15)
    at /usr/local/lib/node_modules/@joystick.js/cli/node_modules/esbuild/lib/main.js:1153:28
    at runOnEndCallbacks (/usr/local/lib/node_modules/@joystick.js/cli/node_modules/esbuild/lib/main.js:943:63)
    at buildResponseToResult (/usr/local/lib/node_modules/@joystick.js/cli/node_modules/esbuild/lib/main.js:1151:7)
    at /usr/local/lib/node_modules/@joystick.js/cli/node_modules/esbuild/lib/main.js:1260:14
    at /usr/local/lib/node_modules/@joystick.js/cli/node_modules/esbuild/lib/main.js:631:9
    at handleIncomingPacket (/usr/local/lib/node_modules/@joystick.js/cli/node_modules/esbuild/lib/main.js:728:9)
    at Socket.readFromStdout (/usr/local/lib/node_modules/@joystick.js/cli/node_modules/esbuild/lib/main.js:598:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Expected "}" but found "button"'
    }
  ],
  warnings: []
}
```
